name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
          
   
    steps:    
      - name: Check out the repository to the runner
        uses: actions/checkout@v1
      - name: Ls
        run: |
            ls -la   
      - name: Create database        
        run: psql -f db/create_db.sql postgresql://postgres:postgres@localhost:5432/postgres   
      - name: Create table script
        run: cat db/tbl*.sql > db/create_tables.sql
      - name: Create tables        
        run: psql -f db/create_tables.sql postgresql://postgres:postgres@localhost:5432/postgres
